### ISSUE TITLE
SOCKS and/or HTTP proxy support?

### ISSUE THREAD

**Issue by mzpqnxow** [openrdap/rdap#18]
I'm wondering what support there is (if any) for SOCKS and HTTP proxies with the `rdap` cli

In theory, to make an RDAP query, only HTTP protocol is required- unless there is some bootstrap mechanism that depends upon DNS (which I realize is possible)

I'm trying to use `rdap` to look up network block metadata in a restrictive environment. To clarify the relevant restrictions:

1. No access to external/public DNS servers
2. No direct UDP/TCP access to Internet resources- must traverse either a SOCKS or HTTP proxy
3. If not HTTP traffic, *must* use SOCKS, can *not* "cheat" by using `CONNECT` in an HTTP proxy

To further clarify, I am *not* interested in WHOIS protocol (UDP/43) so no worries about supporting that

Here's what happens when I try to specify an HTTP proxy and hope for the best:

```
20:05:59 › HTTP_PROXY=http://127.0.0.1:3128 HTTPS_PROXY=http://127.0.0.1:3128 rdap 1.1.1.1
# Error: Get https://data.iana.org/rdap/ipv4.json: dial tcp: lookup data.iana.org on my.internal.resolver:53: no such host
```

Clearly in this case it's grabbing some bootstrap data via HTTP from IANA and not honoring my attempt at specifying a proxy. I'm stuck here because of the restrictions mentioned above

I have yet to look under the hood to see what HTTP package `rdap` is using, but maybe you can save me some time and clarify:

1. Is there is support for HTTP proxying
2. If so, how do I specify the proxy?
3. If not, would either consider implementing it or accept a PR for it?

Thanks!

**Comment by skip2** [comment]
Hi @mzpqnxow,
I've merged https://github.com/openrdap/rdap/commit/8261950e657dbdff759365709e0a6793e4719770, so you can use the HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables.
 
thanks very much,

skip2

**Comment by mzpqnxow** [comment]
> Hi @mzpqnxow,
> 
> I've merged https://github.com/openrdap/rdap/commit/8261950e657dbdff759365709e0a6793e4719770, so you can use the HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables.
> 
>  
> 
> thanks very much,
> 
> 
> 
> skip2

Great, thanks!
