### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by gcmalloc** [openrdap/rdap#3]
Hi, 
Do you plan on making binary release and versioning ? I would be interested to package it for my linux distribution and having a release either binary or link to a specific version could help me greatly.

**Comment by skip2** [comment]
Hey,
This is a good idea, I'm intending to create RPMs for at least fedora, so we'll need version numbers.

Would tagging the current sources as v0.9 be okay?

thanks,

**Comment by gcmalloc** [comment]
It would be perfect, thanks a lot.

**Comment by gcmalloc** [comment]
Thanks :)
